config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :results
  resources :questions
  resources :subjects
  devise_for :users

  root 'quiz#index'
  get 'quiz/check'
  post '/quiz/result'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container-fluid">
    <div class="row">

      <div class="col-md-12 bg-success">
        <div class="navbar">
          <div class="container">

            <%= link_to "Home", root_path,  class: 'navbar-item text-light' %>
          
            <% if user_signed_in? &&(current_user.role =="admin" || current_user.role == "teacher") %>
            <%= link_to "Questions", questions_path,  class: 'navbar-item text-light' %>
            <%= link_to "Subject", subjects_path, class: 'navbar-item text-light' %>
            <% if current_user.role == "admin" %>
            <%= link_to "Score", results_path, class: 'navbar-item text-light' %>
            <% end %>
            <% end %>

            <div class="navbar-text float-right text-light">
              <% if user_signed_in? %>
                <strong><%= current_user.email.split('@').first %>(<%= current_user.role %>)</strong> | 
                <% if current_user.admin? %>
                  <strong> <%= link_to "Admin Panel", rails_admin_path, class: 'navbar-item text-light' %></strong>
                <% end %>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item text-light' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item text-light'  %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item text-light'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-item text-light'  %>
              <% end %>
            </div>

          </div >
        </div>
      </div>  
      
      <div>
        <% if notice %>
          <p class="alert alert-success" ><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>

      <div class="col-md-12" style="min-height:80vh;">
        <%= yield %>
      </div>

      <div class="col-md-12 bg-secondary">
        <div class="container text-center text-light p-3">
          <h4>Quiz Mania 2020</h4>
          <p>This is the quiz contenst that covers almost all the topic of world</p>
          <p>Contact: 09876543</p>
          <p>Email: alfred12@gmail.com</p>
        </div>
      </div>
      
    </div>
  </div>

  </body>
</html>